### PR TITLE
Upper bound on servant

### PR DESCRIPTION
**Pull request by domenkozar**
As per https://github.com/haskell-servant/servant/issues/983

### CODE REVIEW

**Comment by chpatrick** [comment]
Hi Domen, in my experience upper bounds usually cause more problems than they solve. I'd rather leave it up to curation.

**Comment by domenkozar** [comment]
@chpatrick curiously, is there any other problem than having to bump servant each release (~6months), sometimes in vain?

**Comment by chpatrick** [comment]
Well this is a really tiny library so I don't think most servant changes should really affect it. What do you gain with the upper bound apart from extra work?

**Comment by domenkozar** [comment]
Main thing you get is that resolving dependencies always results into known working set, for tools being able to test matrix of options: https://matrix.hackage.haskell.org/package/servant-generic

**Pull request closed without merging**
